notifications:
 email: false

language: node_js

node_js:
 - 6.1

install:
 - "npm install -g typescript"
 - "npm install"
 
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true